version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    FRONTEND_REPO: three-tier-frontend
    BACKEND_REPO: three-tier-backend
    VITE_API_URL: "/api"

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - FRONTEND_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPO}
      - BACKEND_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPO}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - docker build -t ${BACKEND_URI}:${IMAGE_TAG} -f backend/Dockerfile backend
      - docker build -t ${FRONTEND_URI}:${IMAGE_TAG} --build-arg VITE_API_URL=${VITE_API_URL} -f frontend/Dockerfile frontend
  post_build:
    commands:
      - docker push ${BACKEND_URI}:${IMAGE_TAG}
      - docker push ${FRONTEND_URI}:${IMAGE_TAG}
      - printf '[{"name":"backend","imageUri":"%s"},{"name":"frontend","imageUri":"%s"}]' ${BACKEND_URI}:${IMAGE_TAG} ${FRONTEND_URI}:${IMAGE_TAG} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
